/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225753;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class CardTest {
    @Test void CardTest() {
        int defaultNum = 1;
        String defaultMark = "♠";
        Card suped1 = new card(1,"♠");
        assertEquals(defaultNum, suped1.getNum());
    }
}
